<?php

/**
 * @file
 * Contains twitter_timeline.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twitter_timeline_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the twitter_timeline module.
    case 'help.page.twitter_timeline':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Display twitter timeline in a block.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function twitter_timeline_theme() {
  $theme = [];
  $theme['twitter_timeline'] = [
    'variables' => [],
    'template' => 'twitter_timeline',
  ];

  return $theme;
}
